#akmsrst
#apiVersion:  apps/v1
#kind: ReplicaSet
#replicas: 2 or 3
#selector:
#template
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset1
spec:
  replicas: 2
  selector:
   matchLabels:
     env: prod
  template:
   metadata:
    name: pod1
    labels:
     env: prod
   spec:
    containers:
     - name: container1
       image: nginx
       ports:
        - containerPort: 81